name: .NET

on:
  push:
    branches: [ "main", "feature/**", "hotfix/**" ]
  pull_request:
    branches: [ "main", "feature/**", "hotfix/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SwipeNFT.API
    - name: Build
      run: dotnet build SwipeNFT.API --no-restore
    - name: Test
      run: dotnet test SwipeNFT.Tests --no-build --verbosity normal
