name: Angular CI

on:
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main", "feature" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './SwipeNFT.Client/package-lock.json'
    - run: npm ci
      working-directory: './SwipeNFT.Client/'
    
    - name: Build
      run: |
          npm run build --prod
      working-directory: './SwipeNFT.Client/'    
    
    # There is a bug in @nrwl/devkit package that causes this step to fail after lint
    # - wait for next release for a fix https://github.com/nrwl/nx/issues/11653 ng lint still works locally
    # - name: Lint
    #   run: |
    #       npm run lint
    #   working-directory: './SwipeNFT.Client/'
   
    - name: Test
      run: |
          npm run test --prod
      working-directory: './SwipeNFT.Client/'

